
import React from "react";
import { LayoutWrapper, MainBody } from "./index.styled";
import Head from "next/head";

const Layout = ({ children }: { children: React.ReactNode }): JSX.Element => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutWrapper>
        <MainBody>{children}</MainBody>
      </LayoutWrapper>
    </>
  );
};

export default Layout;
